apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foobar

resources:
  - argo-workflow/workflow-template.yaml
  - argo-events/foobar-api/event-source.yaml
  - argo-events/foobar-api/sensor.yaml
  - argo-events/foobar-api/workflow.yaml

