---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: playground 
  namespace: foobar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  namespace: foobar
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-role-binding
  namespace: foobar
subjects:
  - kind: ServiceAccount
    name: foobar 
    namespace: foobar
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io
