name: Build and push foobar-api container image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: foobar-api
  IMAGE_TAG: v0.0.3
  REGISTRY_USER: ambrosiaaaa
  REGISTRY: docker.io

jobs:
  test:
    runs-on: [my-runner-foobar]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: traefik-labs

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Check and run tests
      - name: Check and run tests
        working-directory: traefik-labs/foobar-api
        run: |
          if [ ! -f go.mod ] || [ ! -f go.sum ]; then
            echo "Error: go.mod or go.sum not found!"
            exit 1
          fi
          TEST_FILES=$(find . -name "*_test.go")
          if [ -z "$TEST_FILES" ]; then
             echo "Error: No test files found!"
             exit 1
          fi
          go test ./... -v

  build-and-push-with-kaniko:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Substituir a seção Kaniko por Docker Build/Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./foobar-api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
