---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.mykubernetes.com`) && PathPrefix(`/jaeger`)
      kind: Rule
      services:
        - name: jaeger-query
          port: 16686
  tls:
    secretName: traefik-dashboard-cert
