---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: foobar-webhook
  namespace: foobar
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    foobar-api:
      port: "12000"
      endpoint: "/foobar-webhook"
      method: POST
