---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: foobar-webhook
  namespace: foobar
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    foobar-api:
      repositories:
        - owner: tbernacchi
          repository: traefik-labs
          names:
            - traefik-labs
      webhook:
        endpoint: "/foobar-webhook"
        port: "12000"
        method: POST
      events:
        - push
      branches:
        - "main"
      paths:
        - "foobar-api"
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-webhook-secret
        key: token
