---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certificates-pv
  namespace: traefik-v2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/certificates
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificates-pvc
  namespace: traefik-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
