---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certificados
  namespace: traefik-v2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/certificados
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi4-5  # You can change this to your node name.
  storageClassName: local-certificados
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificados
  namespace: traefik-v2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-certificados
