apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foobar

resources:
  - 005-myapp-secret.yaml
  - 007-myapp-new-pv-pvc.yaml
  - 003-myapp-foo-bar.yaml
  - 006-myapp-metrics.yaml

