apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foobar
resources:
  - 002-myapp-foobar-all.yaml
  - 003-myapp-foobar-secret.yaml
  - 004-myapp-foobar-metrics-ingress.yaml
  - 005-myapp-new-pv-pvc.yaml
  - 006-myapp-foobar-netpol.yaml
images:
  - name: ambrosiaaaaa/foobar-api
    newTag: v0.0.7
