ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true
      options: "default"

dashboard:
  enabled: true
  domain: "traefik.mykubernetes.com"

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=false"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"  #new way of redirect.
  - "--log.level=DEBUG"

  # Disable HSTS
  - "--entrypoints.websecure.http.tls.options.default.minVersion=VersionTLS12"
  - "--entrypoints.websecure.http.tls.options.default.maxVersion=VersionTLS13"

  # TLS e SNI configs
  - "--entrypoints.websecure.http.tls=true"
  - "--entrypoints.websecure.http.tls.options.default.sniStrict=false"
  - "--entrypoints.websecure.http.tls.options.default.minVersion=VersionTLS12"
  - "--entrypoints.websecure.http.tls.options.default.maxVersion=VersionTLS13"
  - "--serversTransport.insecureSkipVerify=true"

# Adicionar essa seção
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"