ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true
      options: default
  metrics:
    port: 8899
    expose: {}
    protocol: TCP

dashboard:
  enabled: true
  domain: "traefik.mykubernetes.com"

metrics:
  prometheus:
    entryPoint: metrics
    service:
      enabled: true
    serviceMonitor:
      enabled: true

logs:
  access:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=false"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--log.level=DEBUG"
  - "--serversTransport.insecureSkipVerify=true"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--entryPoints.metrics.address=:8899"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--tracing.otlp=true"
  - "--tracing.otlp.http=true"
  - "--tracing.otlp.http.endpoint=http://jaeger-collector.observability.svc:4318/v1/traces"

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
