ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true
      options: default

dashboard:
  enabled: true
  domain: "traefik.mykubernetes.com"

metrics:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: prometheus

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=false"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--log.level=DEBUG"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--serversTransport.insecureSkipVerify=true"

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
