name: Build and Push foobar-api

on:
  push:
    paths:
      - 'foobar-api/**'
  pull_request:
    paths:
      - 'foobar-api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build 
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v ./...
