# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'foobar-api/**'
  pull_request:
    paths:
      - 'foobar-api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: foobar-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Initialize Go module
      working-directory: foobar-api
      run: |
        if [ ! -f go.mod ]; then
          go mod init foobar-api
        fi
        go mod tidy

    - name: Build
      working-directory: foobar-api
      run: go build -v ./...

    - name: Test
      working-directory: foobar-api
      run: go test -v ./...
